### ISSUE TITLE
Request: change algorithm to (N + P + K)/max instead of MIN(N, P, K)/max

### ISSUE THREAD

**Issue by AustinHellerRepo** [copygirl/FarmlandDropsSoil#2]
Given that the quality of the soil is a composite of all three nutrients, one would expect that each would contribute to the probability of the soil being returned. For example, if there were 100 different nutrient types with 99 of them at max and one of them was at 0%, that would still leave 99% of the soil in perfect condition yet the current algorithm would result in the drop not spawning.

There are different ways of doing this math that are all equivalent, but I think that the equation below more closely matches the current implementation:

current = (N / max) + (P / max) + (K / max)
prob = current / 3

Example:
N = 80
P = 80
K = 20
max = 80
current = (80 / 80) + (80 / 80) + (20 / 80) = 1 + 1 + 0.25 = 2.25
prob = 2.25 / 3.0 = 0.75

Compare that to the usual "average" equation (to validate suggested equation):
average = (80 + 80 + 20) / 3 = 60
prob = 60 / 80 = 0.75

**Comment by copygirl** [comment]
The is was to allow people to pick up the soil if it has fully recovered its nutrients, and to punish people who are trying to game the system, for example by using a cheap fertilizer to boost the total quality of the soil so they can reset the nutrients of one that would require an expensive fertilizer.

**Comment by copygirl** [comment]
The idea is to allow people to pick up the soil if it has fully recovered its nutrients, and to punish people who are trying to game the system, for example by using a cheap fertilizer to boost the total quality of the soil so they can reset the nutrients of one that would require an expensive fertilizer.

**Comment by AustinHellerRepo** [comment]
I agree that there should be risk, but it seems that focusing on only the lowest nutrient ignores the reality that the other 2/3rds of the soil could be at max. There would still be risk, but it's more realistic in terms of what the soil's state is as a whole. If 2/3rds of the soil is perfect, I would expect that I have a 2/3rds chance of getting back the block.
Players (myself included) would still want to wait for all three nutrients to get near maximum, but they wouldn't be punished unreasonably for not being able to find harder-to-get fertilizer.

Is there a way to add a configuration toggle for which equation would be utilized under the hood? I've never created a mod but I have a great deal of programming experience. If a configuration toggle is possible, would you be open to me submitting a pull request?
I'm thinking that there could be a few different ways that people may prefer:
1. Minimum nutrient (how it is today)
2. Maximum nutrient
3. Average of all nutrients
4. Always pick up the block

Thoughts?

**Comment by copygirl** [comment]
> but they wouldn't be punished unreasonably for not being able to find harder-to-get fertilizer.

Has something in the game changed that I don't know about that would require more than just waiting for the farmland to recover its nutrients on its own, while nothing is growing on it, before moving it without risk?

> Is there a way to add a configuration toggle

Possible? Definitely. But that would seriously complicate a mod that has been incredibly simple, straightforward, and has survived 3.5 years and 4 major versions so far without additional work required. (To be fair I haven't looked into what mods do to get config options, but my intuition says it could be quite a hassle.)

----

Maximum nutrient value is in my opinion essentially equivalent to always picking up the block, which is 1. pretty easy to abuse in my opinion and thus not in the scope of the mod, and 2. pretty easy to do (I believe) with a mod that just tweaks the drops of farmland without any additional code required.

The one way to save the average nutrient option is to clamp the nutrient values to their natural maximum, so even if you boost another nutrient with fertilizer, that wouldn't have any effect on the soil drop chance. Making this change would effectively just increase the drop chance for farmland that's not fully recovered. Personally, I would always wait until the drop chance is 100%, because I don't want to waste *any* of my precious terra preta.

I suppose with all that said, let's take the example of a terra preta farmland block having been drained of all of one of its nutrients, while the others are at max or boosted with fertilizer. That would result in the following drop chances:

- **Minimum nutrient:** `min(120, 80, 0) / 80` = 0%
- **Average nutrients:** `(min(120, 80) + min(80, 80) + min(0, 80)) / 240` = 66.6%

In such an extreme case, I would lean towards not dropping a soil block, which starts with 80/80/80 nutrients when re-tilled, since you have completely removed one of the necessary nutrients, making it unable to grow certain crops at all. A drop-rate of two in three is actually quite high.

One could argue that you wouldn't want to risk even a one in three chance to lose a precious terra preta block, but at that point that just feels like personal preference. The main point is, again, to encourage the player to let the farmland recover.

**Comment by AustinHellerRepo** [comment]
> Has something in the game changed that I don't know about that would require more than just waiting for the farmland to recover its nutrients on its own, while nothing is growing on it, before moving it without risk?

After looking into it, I believe this is the case, that waiting will restore the nutrients over time.

> Maximum nutrient value is in my opinion essentially equivalent to always picking up the block, which is 1

I don't have enough game experience to say, but I get the feeling that you're right about that. Maybe that's a silly configuration option in hindsight.

Other configuration ideas:
* Using a shovel or hands gives a user-configurable multiplier to the probability of dropping for each respective method
* How hungry or healthy you are could reduce the probability, implying that you are too hungry to do the work properly or too tired respectively, inspiring the player to keep some berries on-hand while they work to keep their food up

> boosted with fertilizer

Oh, no. I wouldn't expect anything over max to count since the goal is to provide the player with an expectation that they're getting back a fresh block that they could place back down with restored stats. For the math, it would be capped at the max for the soil type just as your "Average nutrients" math above describes.

> A drop-rate of two in three is actually quite high.

Most of the time the result from the average will always be quite high, but not 100% when casually examined. This high-percentage zone is where I would expect players (myself included) to play more risky (with medium and high fertility soil in the early game - terra preta is something no one would ever gamble with at any stage in the game). The strictness of this mod as-is basically encourages everyone to wait for 100%.

If we examine this more common example:
* Minimum nutrient: `min(65, 65, 55) / 65` = 85%
* Minimum nutrient: `(min(65, 65) + min(65, 65) + min(55, 65)) / 195` = 95%

Someone might be fine with risking a high-fertility block at 95% right now, acting in the moment, and might play more fast-and-loose if they know that the soil is very likely to drop. If we add in other configuration options, players would also strive to have full health, full food, and a shovel. Heck, maybe the user could configure it to only ever hit 99% in the best case (by setting the shovel multiplier to 0.99).
I'm basically just trying to encourage a wider range of supported gameplay options for players.

<hr>

All of that said, I'm only just now beginning my journey into farming. I don't know how hard/easy it is to get back up to max nutrients, how long it takes to wait for 100%, or how hard/easy it is to find fertilizer. I just noticed that the logic of the math seemed to exclude any consideration for the total state of the block, only focusing on the singularly worst quality. It just seemed odd to me at the time.
Maybe as I play more I will find that this mod is perfect as it is, but I get the feeling that since it is more strict than the average case that I'll just end up like everyone else, always waiting for maximum - never feeling inspired in the moment to "just move it now".

Thanks for the discussion. I appreciate your feedback.

**Comment by copygirl** [comment]
There is value to be found in simplicity, so while I won't discourage anyone else from exploring the idea space, your suggestions regarding tool usage and player stats affecting the chance of soil to drop is not a good fit for this mod. Also, I've quit Vintage Story modding for a while now, so it'd have to be a meaningful change for me to consider releasing it. (Though anyone may feel free to fork and make that decision for themselves, as per the (un)license.)

Thank you for the constructive chat! :green_heart:
